// Comprehensive countries + banks dataset for the withdrawal flow.
// The server function `getBanksForCountry` can override this with live data
// from a payment provider (Flutterwave) when a secret key is configured.

export type Country = {
  code: string;       // ISO 3166-1 alpha-2
  name: string;
  flag: string;
  currency: string;
  dial?: string;
};

export type Bank = { name: string; code?: string };

// Full ISO-3166 country list (flags + currencies). Search covers ALL countries.
export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", currency: "AFN" },
  { code: "AL", name: "Albania", flag: "🇦🇱", currency: "ALL" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿", currency: "DZD" },
  { code: "AR", name: "Argentina", flag: "🇦🇷", currency: "ARS" },
  { code: "AM", name: "Armenia", flag: "🇦🇲", currency: "AMD" },
  { code: "AU", name: "Australia", flag: "🇦🇺", currency: "AUD" },
  { code: "AT", name: "Austria", flag: "🇦🇹", currency: "EUR" },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", currency: "AZN" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭", currency: "BHD" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", currency: "BDT" },
  { code: "BY", name: "Belarus", flag: "🇧🇾", currency: "BYN" },
  { code: "BE", name: "Belgium", flag: "🇧🇪", currency: "EUR" },
  { code: "BJ", name: "Benin", flag: "🇧🇯", currency: "XOF" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", currency: "BOB" },
  { code: "BW", name: "Botswana", flag: "🇧🇼", currency: "BWP" },
  { code: "BR", name: "Brazil", flag: "🇧🇷", currency: "BRL" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬", currency: "BGN" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", currency: "XOF" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭", currency: "KHR" },
  { code: "CM", name: "Cameroon", flag: "🇨🇲", currency: "XAF" },
  { code: "CA", name: "Canada", flag: "🇨🇦", currency: "CAD" },
  { code: "CL", name: "Chile", flag: "🇨🇱", currency: "CLP" },
  { code: "CN", name: "China", flag: "🇨🇳", currency: "CNY" },
  { code: "CO", name: "Colombia", flag: "🇨🇴", currency: "COP" },
  { code: "CD", name: "Congo (DRC)", flag: "🇨🇩", currency: "CDF" },
  { code: "CG", name: "Congo (Republic)", flag: "🇨🇬", currency: "XAF" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", currency: "CRC" },
  { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮", currency: "XOF" },
  { code: "HR", name: "Croatia", flag: "🇭🇷", currency: "EUR" },
  { code: "CY", name: "Cyprus", flag: "🇨🇾", currency: "EUR" },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿", currency: "CZK" },
  { code: "DK", name: "Denmark", flag: "🇩🇰", currency: "DKK" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴", currency: "DOP" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", currency: "USD" },
  { code: "EG", name: "Egypt", flag: "🇪🇬", currency: "EGP" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻", currency: "USD" },
  { code: "EE", name: "Estonia", flag: "🇪🇪", currency: "EUR" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹", currency: "ETB" },
  { code: "FI", name: "Finland", flag: "🇫🇮", currency: "EUR" },
  { code: "FR", name: "France", flag: "🇫🇷", currency: "EUR" },
  { code: "GA", name: "Gabon", flag: "🇬🇦", currency: "XAF" },
  { code: "GM", name: "Gambia", flag: "🇬🇲", currency: "GMD" },
  { code: "GE", name: "Georgia", flag: "🇬🇪", currency: "GEL" },
  { code: "DE", name: "Germany", flag: "🇩🇪", currency: "EUR" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", currency: "GHS" },
  { code: "GR", name: "Greece", flag: "🇬🇷", currency: "EUR" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", currency: "GTQ" },
  { code: "HN", name: "Honduras", flag: "🇭🇳", currency: "HNL" },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰", currency: "HKD" },
  { code: "HU", name: "Hungary", flag: "🇭🇺", currency: "HUF" },
  { code: "IS", name: "Iceland", flag: "🇮🇸", currency: "ISK" },
  { code: "IN", name: "India", flag: "🇮🇳", currency: "INR" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", currency: "IDR" },
  { code: "IE", name: "Ireland", flag: "🇮🇪", currency: "EUR" },
  { code: "IL", name: "Israel", flag: "🇮🇱", currency: "ILS" },
  { code: "IT", name: "Italy", flag: "🇮🇹", currency: "EUR" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲", currency: "JMD" },
  { code: "JP", name: "Japan", flag: "🇯🇵", currency: "JPY" },
  { code: "JO", name: "Jordan", flag: "🇯🇴", currency: "JOD" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", currency: "KZT" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", currency: "KES" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼", currency: "KWD" },
  { code: "LV", name: "Latvia", flag: "🇱🇻", currency: "EUR" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧", currency: "LBP" },
  { code: "LR", name: "Liberia", flag: "🇱🇷", currency: "LRD" },
  { code: "LT", name: "Lithuania", flag: "🇱🇹", currency: "EUR" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺", currency: "EUR" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬", currency: "MGA" },
  { code: "MW", name: "Malawi", flag: "🇲🇼", currency: "MWK" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", currency: "MYR" },
  { code: "ML", name: "Mali", flag: "🇲🇱", currency: "XOF" },
  { code: "MT", name: "Malta", flag: "🇲🇹", currency: "EUR" },
  { code: "MU", name: "Mauritius", flag: "🇲🇺", currency: "MUR" },
  { code: "MX", name: "Mexico", flag: "🇲🇽", currency: "MXN" },
  { code: "MD", name: "Moldova", flag: "🇲🇩", currency: "MDL" },
  { code: "MA", name: "Morocco", flag: "🇲🇦", currency: "MAD" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿", currency: "MZN" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲", currency: "MMK" },
  { code: "NA", name: "Namibia", flag: "🇳🇦", currency: "NAD" },
  { code: "NP", name: "Nepal", flag: "🇳🇵", currency: "NPR" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱", currency: "EUR" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿", currency: "NZD" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮", currency: "NIO" },
  { code: "NE", name: "Niger", flag: "🇳🇪", currency: "XOF" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", currency: "NGN" },
  { code: "NO", name: "Norway", flag: "🇳🇴", currency: "NOK" },
  { code: "OM", name: "Oman", flag: "🇴🇲", currency: "OMR" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰", currency: "PKR" },
  { code: "PA", name: "Panama", flag: "🇵🇦", currency: "PAB" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾", currency: "PYG" },
  { code: "PE", name: "Peru", flag: "🇵🇪", currency: "PEN" },
  { code: "PH", name: "Philippines", flag: "🇵🇭", currency: "PHP" },
  { code: "PL", name: "Poland", flag: "🇵🇱", currency: "PLN" },
  { code: "PT", name: "Portugal", flag: "🇵🇹", currency: "EUR" },
  { code: "QA", name: "Qatar", flag: "🇶🇦", currency: "QAR" },
  { code: "RO", name: "Romania", flag: "🇷🇴", currency: "RON" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", currency: "RWF" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", currency: "SAR" },
  { code: "SN", name: "Senegal", flag: "🇸🇳", currency: "XOF" },
  { code: "RS", name: "Serbia", flag: "🇷🇸", currency: "RSD" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱", currency: "SLE" },
  { code: "SG", name: "Singapore", flag: "🇸🇬", currency: "SGD" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰", currency: "EUR" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮", currency: "EUR" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦", currency: "ZAR" },
  { code: "KR", name: "South Korea", flag: "🇰🇷", currency: "KRW" },
  { code: "ES", name: "Spain", flag: "🇪🇸", currency: "EUR" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", currency: "LKR" },
  { code: "SE", name: "Sweden", flag: "🇸🇪", currency: "SEK" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭", currency: "CHF" },
  { code: "TW", name: "Taiwan", flag: "🇹🇼", currency: "TWD" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿", currency: "TZS" },
  { code: "TH", name: "Thailand", flag: "🇹🇭", currency: "THB" },
  { code: "TG", name: "Togo", flag: "🇹🇬", currency: "XOF" },
  { code: "TT", name: "Trinidad & Tobago", flag: "🇹🇹", currency: "TTD" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳", currency: "TND" },
  { code: "TR", name: "Turkey", flag: "🇹🇷", currency: "TRY" },
  { code: "UG", name: "Uganda", flag: "🇺🇬", currency: "UGX" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦", currency: "UAH" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪", currency: "AED" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧", currency: "GBP" },
  { code: "US", name: "United States", flag: "🇺🇸", currency: "USD" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", currency: "UYU" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", currency: "UZS" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", currency: "VES" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", currency: "VND" },
  { code: "ZM", name: "Zambia", flag: "🇿🇲", currency: "ZMW" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", currency: "ZWL" },
];

// Curated bank lists keyed by ISO 3166-1 alpha-2. Used as fallback and for
// countries the payment provider does not cover.
export const BANKS_BY_COUNTRY: Record<string, Bank[]> = {
  NG: [
    { name: "Access Bank" }, { name: "Citibank Nigeria" }, { name: "Ecobank Nigeria" },
    { name: "Fidelity Bank" }, { name: "First Bank of Nigeria" }, { name: "First City Monument Bank (FCMB)" },
    { name: "Globus Bank" }, { name: "Guaranty Trust Bank (GTBank)" }, { name: "Heritage Bank" },
    { name: "Jaiz Bank" }, { name: "Keystone Bank" }, { name: "Kuda Bank" }, { name: "Lotus Bank" },
    { name: "Opay" }, { name: "Palmpay" }, { name: "Parallex Bank" }, { name: "Polaris Bank" },
    { name: "Premium Trust Bank" }, { name: "Providus Bank" }, { name: "Rand Merchant Bank" },
    { name: "Signature Bank" }, { name: "Stanbic IBTC Bank" }, { name: "Standard Chartered Nigeria" },
    { name: "Sterling Bank" }, { name: "SunTrust Bank" }, { name: "TAJ Bank" }, { name: "Titan Trust Bank" },
    { name: "Union Bank of Nigeria" }, { name: "United Bank for Africa (UBA)" }, { name: "Unity Bank" },
    { name: "VFD Bank" }, { name: "Wema Bank" }, { name: "Zenith Bank" }, { name: "Coronation Merchant Bank" },
    { name: "Nova Merchant Bank" }, { name: "Moniepoint" }, { name: "Sparkle Bank" }, { name: "Rubies Bank" },
  ],
  GH: [
    { name: "Ghana Commercial Bank (GCB)" }, { name: "Ecobank Ghana" }, { name: "Absa Bank Ghana" },
    { name: "Standard Chartered Ghana" }, { name: "Zenith Bank Ghana" }, { name: "Fidelity Bank Ghana" },
    { name: "CalBank" }, { name: "Access Bank Ghana" }, { name: "Stanbic Bank Ghana" },
    { name: "Republic Bank Ghana" }, { name: "UBA Ghana" }, { name: "Consolidated Bank Ghana" },
    { name: "ADB Bank" }, { name: "Prudential Bank" }, { name: "Societe Generale Ghana" },
    { name: "First Atlantic Bank" }, { name: "Bank of Africa Ghana" }, { name: "GT Bank Ghana" },
    { name: "Bank Transfer" }, { name: "MTN MoMo" }, { name: "Telecel Cash" }, { name: "AT Money" },
  ],

  KE: [
    { name: "KCB Bank" }, { name: "Equity Bank" }, { name: "Co-operative Bank" }, { name: "Absa Bank Kenya" },
    { name: "Standard Chartered Kenya" }, { name: "Stanbic Bank Kenya" }, { name: "NCBA Bank" },
    { name: "Diamond Trust Bank" }, { name: "I&M Bank" }, { name: "Family Bank" }, { name: "Ecobank Kenya" },
    { name: "Prime Bank" }, { name: "Sidian Bank" }, { name: "Gulf African Bank" }, { name: "HFC Bank" },
  ],
  ZA: [
    { name: "Standard Bank" }, { name: "ABSA Bank" }, { name: "First National Bank (FNB)" }, { name: "Nedbank" },
    { name: "Capitec Bank" }, { name: "Investec" }, { name: "African Bank" }, { name: "Discovery Bank" },
    { name: "TymeBank" }, { name: "Bidvest Bank" }, { name: "Bank Zero" }, { name: "Sasfin Bank" },
    { name: "MTN MoMo" }, { name: "FNB eWallet" },
  ],

  UG: [
    { name: "Stanbic Bank Uganda" }, { name: "Centenary Bank" }, { name: "Absa Bank Uganda" },
    { name: "Standard Chartered Uganda" }, { name: "DFCU Bank" }, { name: "Equity Bank Uganda" },
    { name: "Bank of Africa Uganda" }, { name: "KCB Bank Uganda" }, { name: "Housing Finance Bank" },
    { name: "Post Bank Uganda" }, { name: "Diamond Trust Bank Uganda" },
  ],
  TZ: [
    { name: "CRDB Bank" }, { name: "NMB Bank" }, { name: "NBC Bank" }, { name: "Stanbic Bank Tanzania" },
    { name: "Standard Chartered Tanzania" }, { name: "Absa Bank Tanzania" }, { name: "Exim Bank" },
    { name: "Diamond Trust Bank Tanzania" }, { name: "I&M Bank Tanzania" }, { name: "Equity Bank Tanzania" },
  ],
  RW: [
    { name: "Bank of Kigali" }, { name: "I&M Bank Rwanda" }, { name: "Equity Bank Rwanda" },
    { name: "Access Bank Rwanda" }, { name: "Ecobank Rwanda" }, { name: "GT Bank Rwanda" },
    { name: "Cogebanque" }, { name: "BPR Bank" },
  ],
  CM: [
    { name: "Afriland First Bank" }, { name: "BICEC" }, { name: "Commercial Bank of Cameroon (CBC)" },
    { name: "Ecobank Cameroun" }, { name: "Standard Chartered Cameroon" },
    { name: "Société Générale Cameroun (SGC)" }, { name: "UBA Cameroun" }, { name: "BGFI Bank Cameroun" },
    { name: "Citibank Cameroon" }, { name: "Access Bank Cameroon" }, { name: "Attijariwafa Bank (SCB)" },
    { name: "CCA Bank" }, { name: "La Régionale" }, { name: "Union Bank of Cameroon" },
    { name: "National Financial Credit Bank (NFC)" },
  ],
  CI: [
    { name: "Société Générale Côte d'Ivoire" }, { name: "Ecobank Côte d'Ivoire" }, { name: "SIB" },
    { name: "NSIA Banque" }, { name: "UBA Côte d'Ivoire" }, { name: "BOA Côte d'Ivoire" },
    { name: "BICICI" }, { name: "Access Bank Côte d'Ivoire" }, { name: "Coris Bank" },
  ],
  SN: [
    { name: "CBAO" }, { name: "Ecobank Sénégal" }, { name: "Société Générale Sénégal" },
    { name: "BOA Sénégal" }, { name: "UBA Sénégal" }, { name: "Banque Atlantique" },
    { name: "BICIS" }, { name: "Orabank" },
  ],
  EG: [
    { name: "National Bank of Egypt" }, { name: "Banque Misr" }, { name: "CIB (Commercial International Bank)" },
    { name: "QNB Alahli" }, { name: "HSBC Egypt" }, { name: "Arab African International Bank" },
    { name: "Credit Agricole Egypt" }, { name: "Alexbank" }, { name: "AAIB" }, { name: "Emirates NBD Egypt" },
  ],
  MA: [
    { name: "Attijariwafa Bank" }, { name: "Banque Populaire" }, { name: "BMCE Bank of Africa" },
    { name: "Crédit Agricole du Maroc" }, { name: "CIH Bank" }, { name: "Société Générale Maroc" },
    { name: "BMCI" }, { name: "Al Barid Bank" },
  ],
  US: [
    { name: "JPMorgan Chase" }, { name: "Bank of America" }, { name: "Wells Fargo" }, { name: "Citibank" },
    { name: "U.S. Bank" }, { name: "PNC Bank" }, { name: "Truist Bank" }, { name: "Goldman Sachs Bank" },
    { name: "Capital One" }, { name: "TD Bank" }, { name: "HSBC USA" }, { name: "Charles Schwab Bank" },
    { name: "Ally Bank" }, { name: "American Express Bank" }, { name: "Discover Bank" },
    { name: "Fifth Third Bank" }, { name: "KeyBank" }, { name: "Regions Bank" }, { name: "Citizens Bank" },
    { name: "BMO Harris Bank" }, { name: "Santander Bank US" }, { name: "M&T Bank" }, { name: "Chime" },
    { name: "SoFi Bank" }, { name: "Varo Bank" }, { name: "Cash App" },
  ],
  CA: [
    { name: "Royal Bank of Canada (RBC)" }, { name: "TD Canada Trust" }, { name: "Scotiabank" },
    { name: "Bank of Montreal (BMO)" }, { name: "CIBC" }, { name: "National Bank of Canada" },
    { name: "HSBC Canada" }, { name: "Desjardins" }, { name: "Tangerine" }, { name: "Simplii Financial" },
    { name: "EQ Bank" },
  ],
  GB: [
    { name: "Barclays" }, { name: "HSBC UK" }, { name: "Lloyds Bank" }, { name: "NatWest" },
    { name: "Santander UK" }, { name: "Standard Chartered UK" }, { name: "Nationwide" },
    { name: "Metro Bank" }, { name: "Monzo" }, { name: "Starling Bank" }, { name: "Revolut" },
    { name: "TSB Bank" }, { name: "Halifax" }, { name: "First Direct" }, { name: "Virgin Money" },
    { name: "Co-operative Bank" }, { name: "Bank of Scotland" }, { name: "Chase UK" },
  ],
  DE: [
    { name: "Deutsche Bank" }, { name: "Commerzbank" }, { name: "DZ Bank" }, { name: "KfW" },
    { name: "Sparkasse" }, { name: "Volksbank" }, { name: "N26" }, { name: "ING-DiBa" }, { name: "DKB" },
    { name: "Postbank" }, { name: "HypoVereinsbank (UniCredit)" }, { name: "Comdirect" },
  ],
  FR: [
    { name: "BNP Paribas" }, { name: "Société Générale" }, { name: "Crédit Agricole" }, { name: "LCL" },
    { name: "Crédit Mutuel" }, { name: "Caisse d'Epargne" }, { name: "Banque Populaire" }, { name: "La Banque Postale" },
    { name: "HSBC France" }, { name: "Boursorama Banque" }, { name: "Fortuneo" }, { name: "Hello Bank" },
  ],
  ES: [
    { name: "Banco Santander" }, { name: "BBVA" }, { name: "CaixaBank" }, { name: "Banco Sabadell" },
    { name: "Bankinter" }, { name: "Unicaja Banco" }, { name: "ING España" }, { name: "Openbank" },
    { name: "Kutxabank" }, { name: "Abanca" },
  ],
  IT: [
    { name: "Intesa Sanpaolo" }, { name: "UniCredit" }, { name: "Banco BPM" }, { name: "Monte dei Paschi di Siena" },
    { name: "BPER Banca" }, { name: "Mediobanca" }, { name: "Banca Popolare di Sondrio" }, { name: "Credem" },
    { name: "Fineco Bank" }, { name: "Poste Italiane" },
  ],
  NL: [
    { name: "ING Bank" }, { name: "Rabobank" }, { name: "ABN AMRO" }, { name: "SNS Bank" },
    { name: "Bunq" }, { name: "Triodos Bank" }, { name: "ASN Bank" }, { name: "Knab" },
  ],
  BE: [
    { name: "KBC Bank" }, { name: "BNP Paribas Fortis" }, { name: "ING Belgium" }, { name: "Belfius Bank" },
    { name: "Argenta" }, { name: "AXA Bank" }, { name: "Beobank" },
  ],
  CH: [
    { name: "UBS" }, { name: "Credit Suisse" }, { name: "Raiffeisen Schweiz" }, { name: "PostFinance" },
    { name: "Zürcher Kantonalbank" }, { name: "Julius Baer" }, { name: "Migros Bank" }, { name: "Bank Cler" },
    { name: "Neon" },
  ],
  AT: [
    { name: "Erste Bank" }, { name: "Raiffeisen Bank" }, { name: "Bank Austria (UniCredit)" },
    { name: "BAWAG P.S.K." }, { name: "Volksbank" }, { name: "Hypo Tirol Bank" }, { name: "N26 Austria" },
  ],
  IE: [
    { name: "AIB" }, { name: "Bank of Ireland" }, { name: "Permanent TSB" }, { name: "Ulster Bank" },
    { name: "KBC Bank Ireland" }, { name: "Revolut Ireland" }, { name: "N26 Ireland" },
  ],
  PT: [
    { name: "Caixa Geral de Depósitos" }, { name: "Millennium BCP" }, { name: "Novo Banco" },
    { name: "Santander Totta" }, { name: "BPI" }, { name: "Montepio" }, { name: "Crédito Agrícola" },
  ],
  SE: [
    { name: "Swedbank" }, { name: "Handelsbanken" }, { name: "SEB" }, { name: "Nordea" },
    { name: "Länsförsäkringar Bank" }, { name: "Danske Bank Sweden" }, { name: "ICA Banken" },
  ],
  NO: [
    { name: "DNB" }, { name: "Nordea Norway" }, { name: "SpareBank 1" }, { name: "Danske Bank Norway" },
    { name: "Handelsbanken Norway" }, { name: "Sbanken" },
  ],
  DK: [
    { name: "Danske Bank" }, { name: "Nordea Denmark" }, { name: "Jyske Bank" }, { name: "Sydbank" },
    { name: "Nykredit" }, { name: "Spar Nord Bank" }, { name: "Arbejdernes Landsbank" },
  ],
  FI: [
    { name: "OP Financial Group" }, { name: "Nordea Finland" }, { name: "Danske Bank Finland" },
    { name: "S-Pankki" }, { name: "POP Pankki" }, { name: "Aktia Bank" },
  ],
  PL: [
    { name: "PKO Bank Polski" }, { name: "Bank Pekao" }, { name: "Santander Bank Polska" },
    { name: "mBank" }, { name: "ING Bank Śląski" }, { name: "BNP Paribas Polska" }, { name: "Millennium Bank" },
    { name: "Alior Bank" },
  ],
  IN: [
    { name: "State Bank of India (SBI)" }, { name: "HDFC Bank" }, { name: "ICICI Bank" }, { name: "Axis Bank" },
    { name: "Kotak Mahindra Bank" }, { name: "Punjab National Bank" }, { name: "Bank of Baroda" },
    { name: "Canara Bank" }, { name: "Union Bank of India" }, { name: "IndusInd Bank" }, { name: "Yes Bank" },
    { name: "IDFC First Bank" }, { name: "IDBI Bank" }, { name: "RBL Bank" }, { name: "Federal Bank" },
    { name: "Bandhan Bank" }, { name: "AU Small Finance Bank" }, { name: "Paytm Payments Bank" },
  ],
  PK: [
    { name: "Habib Bank Limited (HBL)" }, { name: "United Bank Limited (UBL)" }, { name: "MCB Bank" },
    { name: "Allied Bank" }, { name: "Bank Alfalah" }, { name: "Standard Chartered Pakistan" },
    { name: "Faysal Bank" }, { name: "Askari Bank" }, { name: "Meezan Bank" }, { name: "JS Bank" },
    { name: "Bank of Punjab" }, { name: "Silkbank" },
  ],
  BD: [
    { name: "Sonali Bank" }, { name: "Janata Bank" }, { name: "Agrani Bank" }, { name: "Dutch-Bangla Bank" },
    { name: "BRAC Bank" }, { name: "Eastern Bank" }, { name: "Prime Bank" }, { name: "City Bank" },
    { name: "Islami Bank Bangladesh" }, { name: "Standard Chartered Bangladesh" }, { name: "HSBC Bangladesh" },
  ],
  AU: [
    { name: "Commonwealth Bank (CBA)" }, { name: "Westpac" }, { name: "ANZ" }, { name: "NAB" },
    { name: "Macquarie Bank" }, { name: "Bendigo Bank" }, { name: "Bank of Queensland" }, { name: "ING Australia" },
    { name: "Suncorp Bank" }, { name: "Up Bank" },
  ],
  NZ: [
    { name: "ANZ New Zealand" }, { name: "ASB Bank" }, { name: "BNZ" }, { name: "Westpac NZ" },
    { name: "Kiwibank" }, { name: "TSB Bank NZ" }, { name: "Heartland Bank" },
  ],
  SG: [
    { name: "DBS Bank" }, { name: "OCBC Bank" }, { name: "UOB" }, { name: "Standard Chartered Singapore" },
    { name: "Citibank Singapore" }, { name: "HSBC Singapore" }, { name: "Maybank Singapore" },
    { name: "CIMB Singapore" }, { name: "Trust Bank" }, { name: "GXS Bank" },
  ],
  MY: [
    { name: "Maybank" }, { name: "CIMB Bank" }, { name: "Public Bank" }, { name: "RHB Bank" },
    { name: "Hong Leong Bank" }, { name: "AmBank" }, { name: "Bank Islam" }, { name: "Alliance Bank" },
    { name: "OCBC Malaysia" }, { name: "HSBC Malaysia" }, { name: "Standard Chartered Malaysia" },
  ],
  ID: [
    { name: "Bank Mandiri" }, { name: "Bank Rakyat Indonesia (BRI)" }, { name: "Bank Central Asia (BCA)" },
    { name: "Bank Negara Indonesia (BNI)" }, { name: "CIMB Niaga" }, { name: "Bank Danamon" },
    { name: "Bank Permata" }, { name: "OCBC NISP" }, { name: "Bank Syariah Indonesia" }, { name: "Jenius" },
    { name: "SeaBank" }, { name: "Bank Jago" },
  ],
  PH: [
    { name: "BDO Unibank" }, { name: "Metrobank" }, { name: "Bank of the Philippine Islands (BPI)" },
    { name: "Land Bank of the Philippines" }, { name: "PNB (Philippine National Bank)" },
    { name: "Security Bank" }, { name: "UnionBank" }, { name: "China Bank" }, { name: "RCBC" },
    { name: "EastWest Bank" }, { name: "GCash" }, { name: "Maya Bank" }, { name: "CIMB Philippines" },
  ],
  TH: [
    { name: "Bangkok Bank" }, { name: "Kasikornbank (KBank)" }, { name: "Krungthai Bank" },
    { name: "Siam Commercial Bank (SCB)" }, { name: "Bank of Ayudhya (Krungsri)" }, { name: "TMBThanachart Bank" },
    { name: "United Overseas Bank Thailand" }, { name: "CIMB Thai" }, { name: "Government Savings Bank" },
  ],
  VN: [
    { name: "Vietcombank" }, { name: "BIDV" }, { name: "VietinBank" }, { name: "Agribank" },
    { name: "Techcombank" }, { name: "MB Bank" }, { name: "VPBank" }, { name: "ACB" }, { name: "Sacombank" },
    { name: "HDBank" }, { name: "TPBank" }, { name: "SHB" },
  ],
  JP: [
    { name: "MUFG Bank" }, { name: "Sumitomo Mitsui Banking (SMBC)" }, { name: "Mizuho Bank" },
    { name: "Resona Bank" }, { name: "Japan Post Bank" }, { name: "Rakuten Bank" }, { name: "SBI Sumishin Net Bank" },
    { name: "Aeon Bank" }, { name: "Seven Bank" },
  ],
  KR: [
    { name: "KB Kookmin Bank" }, { name: "Shinhan Bank" }, { name: "Woori Bank" }, { name: "Hana Bank" },
    { name: "NH NongHyup Bank" }, { name: "Industrial Bank of Korea (IBK)" }, { name: "KakaoBank" },
    { name: "Toss Bank" }, { name: "K Bank" }, { name: "Citibank Korea" },
  ],
  CN: [
    { name: "Industrial and Commercial Bank of China (ICBC)" }, { name: "China Construction Bank (CCB)" },
    { name: "Agricultural Bank of China (ABC)" }, { name: "Bank of China (BOC)" },
    { name: "Bank of Communications" }, { name: "China Merchants Bank" }, { name: "Postal Savings Bank of China" },
    { name: "China CITIC Bank" }, { name: "China Everbright Bank" }, { name: "Ping An Bank" },
  ],
  HK: [
    { name: "HSBC Hong Kong" }, { name: "Hang Seng Bank" }, { name: "Bank of China (Hong Kong)" },
    { name: "Standard Chartered Hong Kong" }, { name: "DBS Hong Kong" }, { name: "Citibank Hong Kong" },
    { name: "Bank of East Asia" }, { name: "Mox Bank" }, { name: "ZA Bank" }, { name: "WeLab Bank" },
  ],
  AE: [
    { name: "Emirates NBD" }, { name: "First Abu Dhabi Bank (FAB)" }, { name: "Abu Dhabi Commercial Bank (ADCB)" },
    { name: "Dubai Islamic Bank" }, { name: "Mashreq Bank" }, { name: "HSBC UAE" },
    { name: "Standard Chartered UAE" }, { name: "Abu Dhabi Islamic Bank (ADIB)" }, { name: "RAKBANK" },
    { name: "Commercial Bank of Dubai" }, { name: "Liv." }, { name: "Wio Bank" },
  ],
  SA: [
    { name: "Al Rajhi Bank" }, { name: "Saudi National Bank (SNB)" }, { name: "Riyad Bank" },
    { name: "Banque Saudi Fransi" }, { name: "Arab National Bank" }, { name: "Bank Albilad" },
    { name: "Bank AlJazira" }, { name: "Alinma Bank" }, { name: "SABB" },
  ],
  IL: [
    { name: "Bank Hapoalim" }, { name: "Bank Leumi" }, { name: "Israel Discount Bank" },
    { name: "Mizrahi-Tefahot Bank" }, { name: "First International Bank of Israel" }, { name: "Bank of Jerusalem" },
    { name: "One Zero Digital Bank" },
  ],
  TR: [
    { name: "Ziraat Bankası" }, { name: "İş Bankası" }, { name: "Garanti BBVA" }, { name: "Yapı Kredi" },
    { name: "Akbank" }, { name: "Halkbank" }, { name: "VakıfBank" }, { name: "QNB Finansbank" },
    { name: "DenizBank" }, { name: "Enpara" },
  ],
  BR: [
    { name: "Banco do Brasil" }, { name: "Itaú Unibanco" }, { name: "Bradesco" }, { name: "Caixa Econômica Federal" },
    { name: "Santander Brasil" }, { name: "Nubank" }, { name: "Banco Inter" }, { name: "BTG Pactual" },
    { name: "Banco Safra" }, { name: "C6 Bank" }, { name: "PicPay" }, { name: "Mercado Pago" },
  ],
  MX: [
    { name: "BBVA México" }, { name: "Citibanamex" }, { name: "Banorte" }, { name: "Santander México" },
    { name: "HSBC México" }, { name: "Scotiabank México" }, { name: "Banco Azteca" }, { name: "Inbursa" },
    { name: "Nu México" }, { name: "Klar" }, { name: "Hey Banco" },
  ],
  AR: [
    { name: "Banco de la Nación Argentina" }, { name: "Banco Santander Argentina" }, { name: "BBVA Argentina" },
    { name: "Banco Galicia" }, { name: "Banco Macro" }, { name: "ICBC Argentina" }, { name: "HSBC Argentina" },
    { name: "Banco Ciudad" }, { name: "Banco Provincia" }, { name: "Mercado Pago" }, { name: "Ualá" },
    { name: "Naranja X" },
  ],
  CL: [
    { name: "Banco de Chile" }, { name: "Banco Santander Chile" }, { name: "BancoEstado" },
    { name: "BCI (Banco de Crédito e Inversiones)" }, { name: "Scotiabank Chile" }, { name: "Itaú Chile" },
    { name: "Banco Falabella" }, { name: "Banco Ripley" }, { name: "Banco Security" }, { name: "MACH" },
  ],
  CO: [
    { name: "Bancolombia" }, { name: "Banco de Bogotá" }, { name: "Davivienda" }, { name: "BBVA Colombia" },
    { name: "Banco Popular" }, { name: "Banco AV Villas" }, { name: "Banco Caja Social" }, { name: "Scotiabank Colpatria" },
    { name: "Nu Colombia" }, { name: "Nequi" }, { name: "Daviplata" },
  ],
  PE: [
    { name: "BCP (Banco de Crédito del Perú)" }, { name: "BBVA Perú" }, { name: "Interbank" }, { name: "Scotiabank Perú" },
    { name: "Banco de la Nación" }, { name: "Banbif" }, { name: "Mibanco" }, { name: "Banco Pichincha Perú" },
  ],
};

// Countries Flutterwave's public /banks endpoint supports.
export const FLW_SUPPORTED = new Set(["NG", "GH", "KE", "UG", "TZ", "ZA", "RW", "CM", "CI", "SN"]);
